(function(){
const page=document.body.dataset.adminPage;
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const esc=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=new Intl.NumberFormat('en-IN');
let cache={centres:[],slots:[],bookings:[],staff:[]};
function feedback(message,error=false){const box=$('#feedback');if(!box)return;box.textContent=message;box.className='feedback show'+(error?' error':'');}
function dateText(value){if(!value)return '—';return new Date(value+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});}
function timeText(value){return String(value||'').slice(0,5);}
function options(rows,placeholder='Select centre'){return `<option value="">${placeholder}</option>`+rows.map(row=>`<option value="${row.id}">${esc(row.name)} · ${esc(row.district)}</option>`).join('');}
async function requireAdmin(){const user=await guard('admin');if(!user)return false;return true;}

async function loadCentres(){const{data,error}=await client().from('centres').select('*').order('name');if(error){feedback(error.message,true);return}cache.centres=data||[];const body=$('#centreRows');if(body)body.innerHTML=cache.centres.map(centre=>`<tr><td><div class="primary-cell"><span class="cell-icon material-symbols-outlined">storefront</span><span><b>${esc(centre.name)}</b><small>${esc(centre.location)}</small></span></div></td><td>${esc(centre.district)}</td><td><b>${fmt.format(centre.capacity_per_slot)}</b> tokens</td><td>${esc(centre.operating_hours)}</td><td><span class="trend">● Active</span></td><td><button class="row-action material-symbols-outlined" aria-label="Edit ${esc(centre.name)}" data-edit-centre="${centre.id}">edit</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty-state"><span class="material-symbols-outlined">storefront</span>No mandi centres yet. Add the first centre using the form.</td></tr>';setText('#centreCount',cache.centres.length);setText('#totalCapacity',cache.centres.reduce((sum,row)=>sum+Number(row.capacity_per_slot||0),0));setText('#districtCount',new Set(cache.centres.map(row=>row.district)).size);$$('[data-edit-centre]').forEach(button=>button.onclick=()=>editCentre(button.dataset.editCentre));}
function editCentre(id){const centre=cache.centres.find(row=>row.id===id);if(!centre)return;const form=$('#centreForm');form.elements.id.value=centre.id;form.elements.name.value=centre.name;form.elements.location.value=centre.location;form.elements.district.value=centre.district;form.elements.capacity_per_slot.value=centre.capacity_per_slot;form.elements.operating_hours.value=centre.operating_hours;$('#centreSubmit').textContent='Update centre';$('#centreCancel').classList.remove('hidden');form.scrollIntoView({behavior:'smooth',block:'center'});}
function resetCentreForm(){const form=$('#centreForm');form.reset();form.elements.id.value='';$('#centreSubmit').textContent='Save centre';$('#centreCancel').classList.add('hidden');}
async function saveCentre(event){event.preventDefault();const values=Object.fromEntries(new FormData(event.target));const id=values.id;delete values.id;values.capacity_per_slot=Number(values.capacity_per_slot);const query=id?client().from('centres').update(values).eq('id',id):client().from('centres').insert(values);const{error}=await query;if(error)return feedback(error.message,true);feedback(id?'Centre updated successfully.':'Centre added successfully.');resetCentreForm();await loadCentres();}

async function loadSlots(){const[centresResult,slotsResult]=await Promise.all([client().from('centres').select('*').order('name'),client().from('slots').select('*,centres(name,district)').order('date',{ascending:false}).order('start_time')]);if(centresResult.error||slotsResult.error)return feedback(centresResult.error?.message||slotsResult.error?.message,true);cache.centres=centresResult.data||[];cache.slots=slotsResult.data||[];$('#slotCentre').innerHTML=options(cache.centres);$('#slotCentreFilter').innerHTML=options(cache.centres,'All centres');renderSlots();setText('#slotCount',cache.slots.length);setText('#openTokenCount',cache.slots.reduce((sum,row)=>sum+Math.max(0,row.max_tokens-row.tokens_booked),0));setText('#bookedTokenCount',cache.slots.reduce((sum,row)=>sum+Number(row.tokens_booked||0),0));updatePreview();}
function filteredSlots(){const centre=$('#slotCentreFilter')?.value,date=$('#slotDateFilter')?.value;return cache.slots.filter(row=>(!centre||row.centre_id===centre)&&(!date||row.date===date));}
function renderSlots(){const rows=filteredSlots(),body=$('#slotRows');body.innerHTML=rows.map(slot=>{const used=slot.max_tokens?Math.round((slot.tokens_booked/slot.max_tokens)*100):0;return `<tr><td><div class="primary-cell"><span class="cell-icon material-symbols-outlined">calendar_month</span><span><b>${dateText(slot.date)}</b><small>${timeText(slot.start_time)}–${timeText(slot.end_time)}</small></span></div></td><td>${esc(slot.centres?.name||'—')}<small style="display:block;color:var(--ref-muted)">${esc(slot.centres?.district||'')}</small></td><td><b>${slot.tokens_booked}/${slot.max_tokens}</b><div class="meter" style="width:110px;margin:6px 0 0"><i style="width:${used}%"></i></div></td><td><span class="${used>=100?'chip no_show':'trend'}">${used>=100?'Full':'Open'}</span></td></tr>`}).join('')||'<tr><td colspan="4" class="empty-state"><span class="material-symbols-outlined">event_busy</span>No slots match these filters.</td></tr>';setText('#slotResultCount',rows.length);}
function localDateValue(date=new Date()){const year=date.getFullYear(),month=String(date.getMonth()+1).padStart(2,'0'),day=String(date.getDate()).padStart(2,'0');return `${year}-${month}-${day}`;}
function datesBetween(from,to){const dates=[],fromParts=String(from).split('-').map(Number),toParts=String(to).split('-').map(Number);if(fromParts.length!==3||toParts.length!==3||fromParts.some(Number.isNaN)||toParts.some(Number.isNaN))return dates;const cursor=new Date(Date.UTC(fromParts[0],fromParts[1]-1,fromParts[2])),end=new Date(Date.UTC(toParts[0],toParts[1]-1,toParts[2]));while(cursor<=end&&dates.length<32){dates.push(cursor.toISOString().slice(0,10));cursor.setUTCDate(cursor.getUTCDate()+1)}return dates;}
function slotTimes(start,end,duration){const rows=[];let cursor=Number(start.slice(0,2))*60+Number(start.slice(3,5)),finish=Number(end.slice(0,2))*60+Number(end.slice(3,5));while(cursor+duration<=finish){const format=minutes=>`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}:00`;rows.push([format(cursor),format(cursor+duration)]);cursor+=duration}return rows;}
function updatePreview(){const form=$('#slotForm');if(!form)return;const from=form.elements.date_from.value,to=form.elements.date_to.value,duration=Number(form.elements.duration.value||60),start=form.elements.start_time.value,end=form.elements.end_time.value;if(!from||!to||!start||!end){setText('#batchPreview','Choose a date range and operating window to preview the batch.');return}const days=datesBetween(from,to).length,times=slotTimes(start,end,duration).length;setText('#batchPreview',`This will create ${days*times} slots across ${days} day${days===1?'':'s'} (${times} per day).`);}
async function generateSlots(event){event.preventDefault();const form=event.target,centreId=form.elements.centre_id.value,dates=datesBetween(form.elements.date_from.value,form.elements.date_to.value),times=slotTimes(form.elements.start_time.value,form.elements.end_time.value,Number(form.elements.duration.value)),maximum=Number(form.elements.max_tokens.value);if(!dates.length||!times.length)return feedback('Check the date range and operating hours.',true);const rows=dates.flatMap(date=>times.map(([start_time,end_time])=>({centre_id:centreId,date,start_time,end_time,max_tokens:maximum})));const{error}=await client().from('slots').upsert(rows,{onConflict:'centre_id,date,start_time',ignoreDuplicates:true});if(error)return feedback(error.message,true);feedback(`${rows.length} slot windows processed successfully.`);await loadSlots();}

async function loadBookings(){const[centresResult,bookingsResult]=await Promise.all([client().from('centres').select('id,name,district').order('name'),client().from('bookings').select('id,token_number,produce_type,quantity,status,payment_status,created_at,profiles!bookings_farmer_id_fkey(name,phone),slots(date,start_time,end_time,centre_id,centres(id,name,district))').order('created_at',{ascending:false})]);if(centresResult.error||bookingsResult.error)return feedback(centresResult.error?.message||bookingsResult.error?.message,true);cache.centres=centresResult.data||[];cache.bookings=bookingsResult.data||[];$('#bookingCentre').innerHTML=options(cache.centres,'All centres');renderBookings();setText('#bookingTotal',cache.bookings.length);setText('#queueTotal',cache.bookings.filter(row=>['confirmed','in_queue'].includes(row.status)).length);setText('#paidTotal',cache.bookings.filter(row=>row.payment_status==='paid').length);}
function filteredBookings(){const search=($('#bookingSearch')?.value||'').toLowerCase(),centre=$('#bookingCentre')?.value,status=$('#bookingStatus')?.value,date=$('#bookingDate')?.value;return cache.bookings.filter(row=>{const haystack=`${row.token_number} ${row.profiles?.name||''} ${row.profiles?.phone||''} ${row.produce_type||''} ${row.slots?.centres?.name||''}`.toLowerCase();return(!search||haystack.includes(search))&&(!centre||row.slots?.centre_id===centre)&&(!status||row.status===status)&&(!date||row.slots?.date===date)});}
function renderBookings(){const rows=filteredBookings(),body=$('#bookingRows');body.innerHTML=rows.map(row=>`<tr><td><b style="color:var(--ref-primary)">#${String(row.token_number).padStart(2,'0')}</b><small style="display:block;color:var(--ref-muted)">${String(row.id).slice(0,8).toUpperCase()}</small></td><td><div class="primary-cell"><span class="cell-icon material-symbols-outlined">person</span><span><b>${esc(row.profiles?.name||'Farmer')}</b><small>${esc(row.profiles?.phone||'')}</small></span></div></td><td>${esc(row.slots?.centres?.name||'—')}<small style="display:block;color:var(--ref-muted)">${dateText(row.slots?.date)} · ${timeText(row.slots?.start_time)}</small></td><td>${esc(row.produce_type||'—')}<small style="display:block;color:var(--ref-muted)">${row.quantity?`${fmt.format(row.quantity)} Qtl`:''}</small></td><td><select class="status-select" data-booking-status="${row.id}" aria-label="Update booking status"><option value="booked" ${row.status==='booked'?'selected':''}>Booked</option><option value="confirmed" ${row.status==='confirmed'?'selected':''}>Confirmed</option><option value="in_queue" ${row.status==='in_queue'?'selected':''}>In queue</option><option value="procured" ${row.status==='procured'?'selected':''}>Procured</option><option value="paid" ${row.status==='paid'?'selected':''}>Paid</option><option value="no_show" ${row.status==='no_show'?'selected':''}>No show</option></select></td><td>${statusChip(row.payment_status)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty-state"><span class="material-symbols-outlined">receipt_long</span>No bookings match these filters.</td></tr>';setText('#bookingResultCount',rows.length);$$('[data-booking-status]').forEach(select=>select.onchange=()=>updateBooking(select.dataset.bookingStatus,select.value));}
async function updateBooking(id,status){const values={status};if(status==='paid'){const entered=prompt('Enter the final amount paid to the farmer (₹):');if(entered===null)return loadBookings();const amount=Number(entered);if(!Number.isFinite(amount)||amount<=0){feedback('Enter a valid payment amount before marking this booking paid.',true);return loadBookings()}values.payment_status='paid';values.amount_paid=Math.round(amount*100)/100;values.paid_at=new Date().toISOString()}const{error}=await client().from('bookings').update(values).eq('id',id);if(error)return feedback(/amount_paid|paid_at/i.test(error.message||'')?'Apply migration 202609100004_operator_payment_amount.sql before recording payments.':error.message,true);feedback(status==='paid'?`Payment of ₹${values.amount_paid.toLocaleString('en-IN',{minimumFractionDigits:2})} recorded and sent to the farmer inbox.`:'Booking status updated. The farmer will receive an inbox notification.');await loadBookings();}

async function loadStaff(){const[centresResult,staffResult]=await Promise.all([client().from('centres').select('id,name,district').order('name'),client().from('profiles').select('id,name,phone,status,centre_id,created_at,centres(name,district)').eq('role','operator').order('created_at',{ascending:false})]);if(centresResult.error||staffResult.error)return feedback(centresResult.error?.message||staffResult.error?.message,true);cache.centres=centresResult.data||[];cache.staff=staffResult.data||[];$('#staffCentre').innerHTML=options(cache.centres);renderStaff();setText('#staffTotal',cache.staff.length);setText('#activeStaff',cache.staff.filter(row=>row.status==='active').length);setText('#assignedStaff',cache.staff.filter(row=>row.centre_id).length);}
function renderStaff(){const body=$('#staffRows');body.innerHTML=cache.staff.map(row=>`<tr><td><div class="primary-cell"><span class="avatar">${esc((row.name||'OP').split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase())}</span><span><b>${esc(row.name)}</b><small>Operator account</small></span></div></td><td>${esc(row.phone)}</td><td>${esc(row.centres?.name||'Unassigned')}<small style="display:block;color:var(--ref-muted)">${esc(row.centres?.district||'')}</small></td><td><span class="${row.status==='active'?'trend':'chip booked'}">● ${esc(row.status)}</span></td><td><button class="row-action material-symbols-outlined" data-toggle-staff="${row.id}" data-status="${row.status}" aria-label="Change ${esc(row.name)} status">${row.status==='active'?'person_off':'person_check'}</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty-state"><span class="material-symbols-outlined">badge</span>No operator accounts yet.</td></tr>';$$('[data-toggle-staff]').forEach(button=>button.onclick=()=>toggleStaff(button.dataset.toggleStaff,button.dataset.status));}
async function toggleStaff(id,status){const next=status==='active'?'inactive':'active';const{error}=await client().from('profiles').update({status:next}).eq('id',id);if(error)return feedback(error.message,true);feedback(`Operator marked ${next}.`);await loadStaff();}
async function createOperator(event){event.preventDefault();const button=event.submitter;button.disabled=true;const values=Object.fromEntries(new FormData(event.target));const{data,error}=await client().functions.invoke('create-staff',{body:values});button.disabled=false;if(error){const unreachable=error.name==='FunctionsFetchError'||/failed to send|fetch/i.test(error.message);return feedback(unreachable?'The operator service is not reachable yet. Deploy the updated create-staff Edge Function in Supabase, then try again.':(data?.error||error.message),true)}const password=data?.temporary_password||data?.temporaryPassword;feedback(password?`Operator created. Temporary password: ${password}`:'Operator created successfully.');event.target.reset();await loadStaff();}
function setText(selector,value){const node=$(selector);if(node)node.textContent=typeof value==='number'?fmt.format(value):value;}
async function init(){if(!await requireAdmin())return;if(page==='centres'){window.saveCentre=saveCentre;window.resetCentreForm=resetCentreForm;await loadCentres()}if(page==='slots'){window.generateSlots=generateSlots;$$('#slotForm input,#slotForm select').forEach(node=>node.addEventListener('change',updatePreview));$('#slotCentreFilter').onchange=renderSlots;$('#slotDateFilter').onchange=renderSlots;const today=localDateValue();$('#slotForm').elements.date_from.value=today;$('#slotForm').elements.date_to.value=today;await loadSlots()}if(page==='bookings'){['#bookingSearch','#bookingCentre','#bookingStatus','#bookingDate'].forEach(selector=>$(selector)?.addEventListener(selector==='#bookingSearch'?'input':'change',renderBookings));await loadBookings();client().channel('admin-bookings-page').on('postgres_changes',{event:'*',schema:'public',table:'bookings'},loadBookings).subscribe()}if(page==='staff'){window.createOperator=createOperator;await loadStaff()}}
init();
})();
